name: Docker-Based Samsung S24 Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-with-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build APK with Buildozer Docker
      run: |
        # Create simple test app
        cat > main.py << 'EOF'
        from kivy.app import App
        from kivy.uix.boxlayout import BoxLayout
        from kivy.uix.label import Label
        from kivy.uix.button import Button

        class Samsung24App(App):
            def build(self):
                layout = BoxLayout(orientation='vertical', padding=20, spacing=10)
                
                title = Label(
                    text='📱 Samsung S24 CPD Tracker\n✅ Docker Build Test',
                    font_size='20sp'
                )
                layout.add_widget(title)
                
                btn = Button(
                    text='🚀 Ready for Samsung S24!',
                    size_hint_y=None,
                    height=50
                )
                layout.add_widget(btn)
                
                return layout

        Samsung24App().run()
        EOF
        
        # Create buildozer spec
        cat > buildozer.spec << 'EOF'
        [app]
        title = Samsung S24 CPD
        package.name = cpds24
        package.domain = org.cpd.s24
        source.dir = .
        source.include_exts = py
        version = 1.0
        requirements = python3,kivy
        orientation = portrait
        fullscreen = 0

        [buildozer]
        log_level = 2

        [android]
        android.api = 31
        android.minapi = 21
        android.archs = arm64-v8a
        android.permissions = CAMERA,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE,INTERNET
        android.release_artifact = apk
        EOF
        
        # Build with official buildozer Docker image
        docker run --rm -v "$(pwd)":/home/user/hostcwd kivy/buildozer android debug
        
    - name: List build output
      run: |
        echo "Build directory contents:"
        ls -la
        if [ -d "bin" ]; then
          echo "APK files:"
          ls -la bin/
        fi
        
    - name: Upload Samsung S24 APK
      uses: actions/upload-artifact@v4
      with:
        name: Samsung-S24-Docker-Build
        path: bin/*.apk
        if-no-files-found: error
