name: Ultra-Minimal Samsung S24 APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Install buildozer
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-11-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip3 install --upgrade pip setuptools wheel
        pip3 install buildozer==1.4.0 cython==0.29.33
        
    - name: Create ultra-minimal app
      run: |
        cat > main.py << 'EOF'
        from kivy.app import App
        from kivy.uix.label import Label

        class TestApp(App):
            def build(self):
                return Label(text='Samsung S24 Test APK\nBuild Success!')

        TestApp().run()
        EOF
        
    - name: Create minimal buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
        [app]
        title = S24Test
        package.name = s24test
        package.domain = org.test
        source.dir = .
        source.include_exts = py
        version = 0.1
        requirements = python3,kivy
        orientation = portrait

        [buildozer]
        log_level = 2

        [android]
        android.api = 30
        android.minapi = 21
        android.ndk = 23b
        android.sdk = 30
        android.archs = arm64-v8a
        android.permissions = INTERNET
        android.release_artifact = apk
        EOF
        
    - name: Build APK
      run: |
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Samsung-S24-Minimal-Test
        path: bin/*.apk
